# Generated by Django 3.1.7 on 2021-02-28 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ingredient')),
                ('dimension', models.CharField(max_length=255, verbose_name='unit of measurement')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='count')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count', to='recipes.ingredient', verbose_name='ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15, verbose_name='tag')),
                ('color', models.CharField(max_length=15, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='recipe')),
                ('photo', models.ImageField(upload_to='recipes/')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='cooking time')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publication time')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('author', models.ForeignKey(on_delete=models.SET(recipes.models.get_unknown_user), related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='recipes.IngredientCount', verbose_name='ingredient')),
                ('tag', models.ManyToManyField(related_name='recipes', to='recipes.Tag', verbose_name='tag')),
            ],
        ),
    ]
