# Generated by Django 3.1.7 on 2021-03-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default=1, max_length=15, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
