# Generated by Django 3.1.7 on 2021-03-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210314_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcount',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='count'),
        ),
    ]
