# Generated by Django 3.1.7 on 2021-03-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210317_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientcount',
            old_name='count',
            new_name='amount',
        ),
    ]
